# Generated by Django 2.1 on 2018-09-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfb_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuron',
            old_name='anatomical_type',
            new_name='neuron_type',
        ),
        migrations.AddField(
            model_name='neuron',
            name='project',
            field=models.CharField(default='p1', max_length=200),
            preserve_default=False,
        ),
    ]
