# Generated by Django 2.1 on 2018-09-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfb_server', '0002_auto_20180903_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuron',
            name='classification_comment',
            field=models.CharField(default='', help_text='Comment on classification of neuron.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neuronsimple',
            name='classification_comment',
            field=models.CharField(default='', help_text='Comment on classification of neuron.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neuronsimple',
            name='project',
            field=models.CharField(choices=[('LC', 'L1EM_Cardona'), ('F', 'FAFB')], default='', help_text='A valid name for a project.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neuron',
            name='project',
            field=models.CharField(choices=[('LC', 'L1EM_Cardona'), ('F', 'FAFB')], help_text='A valid name for a project.', max_length=200),
        ),
    ]
