# Generated by Django 2.1 on 2018-09-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfb_server', '0005_auto_20180903_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuron',
            name='alternative_names',
            field=models.CharField(help_text='Tube (|) seperated list of alternative terms (i.e. synonyms).', max_length=1000),
        ),
    ]
