# Generated by Django 2.1 on 2018-09-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfb_server', '0006_auto_20180903_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('orcid', models.URLField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('orcid',),
            },
        ),
    ]
